### ISSUE TITLE
snapper.checkout seems to not handle directories (maybe I'm being dumb)

### ISSUE THREAD

**Issue by hdamron17** [jyn514/Colahacks#14]

**Comment by jyn514** [comment]
~~Whoops, had this locally for the past few months. Pushing as soon as I fix merge conflicts.~~ this was `main.checkout`, ignore this

**Comment by jyn514** [comment]
Found the problem. It handles top-level directories but not subdirectories. Example:

```
 % ./snapper.py ~/Programming/Python/scraping
Traceback (most recent call last):
  File "./snapper.py", line 223, in <module>
    print(main(**{k: v for k, v in parser.parse_args().__dict__.items()
  File "./snapper.py", line 205, in main
    savedir, tmpdir = checkout(files, previous, commit, directory)
  File "./snapper.py", line 120, in checkout
    with open(tmpfile) as original:  # should have been checked out by git
IsADirectoryError: [Errno 21] Is a directory: '/tmp/snap/scraping/books'
```

Thanks for letting me know, I'm working on a fix.

**Comment by jyn514** [comment]
This is actually a problem with `flatten`, not checkout. Files should all be resolved by the time they're passed to `checkout`.

I guess we should consider the case of an empty directory of some point, but I want to fix this first.

**Comment by jyn514** [comment]
~~Got it. If `git ls-tree` is passed a directory with a slash appended, it'll just return the same thing it got. Fixing now.~~ This was already being done.

**Comment by jyn514** [comment]
Found it for real this time. `os.isdir` was in the wrong working directory.

**Comment by jyn514** [comment]
Fixed in https://github.com/jyn514/Colahacks/commit/f49ee7470951e59fdea310c91804eaf70b9d7f24
