### ISSUE TITLE
Git-based versioning does not provide ordering information to front-end

### ISSUE THREAD

**Issue by hdamron17** [jyn514/Colahacks#15]

**Comment by jyn514** [comment]
~~Right, remember that we were going to walk the parent tree? I'm still hoping to find a third-party tool but until then we'll have to write our own function.~~

Looks like you're using [gitgraph](http://gitgraphjs.com/)

**Comment by jyn514** [comment]
Took a look at this, `git rev-list --parents` does most of what we need. If you can pass back the current commit I could probably pass back the parents and children to an arbitrary depth.

**Comment by jyn514** [comment]
Done in https://github.com/jyn514/Colahacks/commit/7078188ef4bcaa0ecc744d4af880452ba8979b4b
