### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by jyn514** [jyn514/Colahacks#3]
I have no idea how the php server runs; we should add that to the README

**Comment by jyn514** [comment]
php -t . -S localhost:4000

**Comment by Brenn10** [comment]
Sudo service apache2 start

**Comment by jyn514** [comment]
that doesn't show the file in the current directory, at least for me. It shows the default page in /var/www/html/index.html.

**Comment by Brenn10** [comment]
Place the package into /var/www/html/ and delete the current index.html such that your index.php is in the html folder

**Comment by jyn514** [comment]
Added in https://github.com/jyn514/Colahacks/commit/2692a23b4be4baebcbf9b36c1d277c0359f0a6b9
